### ISSUE TITLE
Text textures is shown before the video starts playing

### ISSUE THREAD

**Issue by timelessnesses** [osudroid/osu-droid#318] opened 2024-01-20 13:19 UTC
### Issue description

- Expected result: Expecting to only play videos and show nothing else
- Actual result: Before video starts playing there's text texture on the top left before its gone and video starts playing

### Steps to reproduce the issue
1. Play a map with video as background and enable video background option

#### Additional details / Screenshot / Clip
- https://youtu.be/dI5n_0cdAOI
### Versions
* Android version: 10
* Game version: 1.7.2P-1

### Crashdump, backtrace or other files
None

**Comment by ammarasyad** [comment] 2024-02-10 10:05
Across 4 devices (2 phones running Android 13 and 14, 2 emulators running Android 10 and 14), I seem to only be able to replicate this issue on the Android 13 device. Is your phone equipped with a Mali GPU by chance?

**Comment by ammarasyad** [comment] 2024-02-11 11:47
In this build, the issue is fixed on my secondary phone (Exynos 9810 with a Mali-G72 GPU). Please test the build on your device, attached below.

I modified the video alpha to 100% in this build to make testing easier. It will not make it to the final build.

[osu!droid-1.7.2(240211)-debug-2024-02-11.zip](https://github.com/osudroid/osu-droid/files/14232178/osu.droid-1.7.2.240211.-debug-2024-02-11.zip)

**Comment by timelessnesses** [comment] 2024-02-17 03:58
> Across 4 devices (2 phones running Android 13 and 14, 2 emulators running Android 10 and 14), I seem to only be able to replicate this issue on the Android 13 device. Is your phone equipped with a Mali GPU by chance?

my android phone is currently android 10 with Mali G51-MP4 to it

**Comment by timelessnesses** [comment] 2024-02-17 04:04
> In this build, the issue is fixed on my secondary phone (Exynos 9810 with a Mali-G72 GPU). Please test the build on your device, attached below.
> 
> I modified the video alpha to 100% in this build to make testing easier. It will not make it to the final build.
> 
> [osu!droid-1.7.2(240211)-debug-2024-02-11.zip](https://github.com/osudroid/osu-droid/files/14232178/osu.droid-1.7.2.240211.-debug-2024-02-11.zip)
> 

i have installed this debug build and first start up it runs fine with no wrong textures being shown on screen  
however when trying to pause the game it just doesnt let me to and i had to force stop it  
now it won't even turn on and give me a black screen

**Comment by timelessnesses** [comment] 2024-02-17 04:07
> > In this build, the issue is fixed on my secondary phone (Exynos 9810 with a Mali-G72 GPU). Please test the build on your device, attached below.
> > 
> > I modified the video alpha to 100% in this build to make testing easier. It will not make it to the final build.
> > 
> > [osu!droid-1.7.2(240211)-debug-2024-02-11.zip](https://github.com/osudroid/osu-droid/files/14232178/osu.droid-1.7.2.240211.-debug-2024-02-11.zip)
> > 
> 
> i have installed this debug build and first start up it runs fine with no wrong textures being shown on screen  
> however when trying to pause the game it just doesnt let me to and i had to force stop it  
> now it won't even run and give me a black screen

somehow running stable build first then run debug after that fixed this problem and now its normal

**Closed** 2024-06-29 13:36 UTC
Labels: bug
